package hotel2;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;


public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage
     */
    Room1 r1=new Room1(); 
    Room2 r2=new Room2(); 
    Room3 r3=new Room3();
    public StartPage() {
        initComponents();
//        Room1 r1=new Room1();
//        Room2 r2=new Room2();
//        Room3 r3=new Room3();
//        r2.Total_Price();
//        double total_price;
        ButtonGroup group = new ButtonGroup();
        group.add(SelcRoom1);
        group.add(SelcRoom2);
        group.add(SelcRoom3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Welcome = new javax.swing.JLabel();
        selectRT = new javax.swing.JLabel();
        SelcRoom1 = new javax.swing.JRadioButton();
        SelcRoom2 = new javax.swing.JRadioButton();
        SelcRoom3 = new javax.swing.JRadioButton();
        Room1Info = new javax.swing.JButton();
        Room2Info = new javax.swing.JButton();
        Room3Info = new javax.swing.JButton();
        GetInfo = new javax.swing.JLabel();
        NoNights = new javax.swing.JLabel();
        NoBeds = new javax.swing.JLabel();
        NoMeal = new javax.swing.JLabel();
        GetNight = new javax.swing.JTextField();
        GetBed = new javax.swing.JTextField();
        GetMeal = new javax.swing.JTextField();
        MaxBed = new javax.swing.JLabel();
        MaxMeal = new javax.swing.JLabel();
        TPrice = new javax.swing.JButton();
        GoToPayment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("StartPage"); // NOI18N

        Welcome.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        Welcome.setForeground(new java.awt.Color(0, 153, 153));
        Welcome.setText("Hotel Reservation");

        selectRT.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        selectRT.setForeground(new java.awt.Color(153, 153, 0));
        selectRT.setText("Please select the room type : ");

        SelcRoom1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        SelcRoom1.setText(" Standard");
        SelcRoom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelcRoom1ActionPerformed(evt);
            }
        });

        SelcRoom2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        SelcRoom2.setText(" Deluxe");
        SelcRoom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelcRoom2ActionPerformed(evt);
            }
        });

        SelcRoom3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        SelcRoom3.setText(" Suite");
        SelcRoom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelcRoom3ActionPerformed(evt);
            }
        });

        Room1Info.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        Room1Info.setText("Info");
        Room1Info.setAlignmentY(0.0F);
        Room1Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room1InfoActionPerformed(evt);
            }
        });

        Room2Info.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        Room2Info.setText("Info");
        Room2Info.setAlignmentY(0.0F);
        Room2Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room2InfoActionPerformed(evt);
            }
        });

        Room3Info.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        Room3Info.setText("Info");
        Room3Info.setAlignmentY(0.0F);
        Room3Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room3InfoActionPerformed(evt);
            }
        });

        GetInfo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        GetInfo.setForeground(new java.awt.Color(153, 153, 0));
        GetInfo.setText("Please enter the following information : ");

        NoNights.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        NoNights.setText("Number of Nights : ");

        NoBeds.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        NoBeds.setText("Number of Beds : ");

        NoMeal.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        NoMeal.setText("Number of Meals : ");

        GetNight.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        GetNight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetNightActionPerformed(evt);
            }
        });

        GetBed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        GetBed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetBedActionPerformed(evt);
            }
        });

        GetMeal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        GetMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetMealActionPerformed(evt);
            }
        });

        MaxBed.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MaxBed.setForeground(new java.awt.Color(204, 0, 0));
        MaxBed.setText("(MAX : 3 Beds)");

        MaxMeal.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MaxMeal.setForeground(new java.awt.Color(204, 0, 51));
        MaxMeal.setText("(MAX : 3 Meals)");

        TPrice.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        TPrice.setText("Show Total Price");
        TPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPriceActionPerformed(evt);
            }
        });

        GoToPayment.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        GoToPayment.setText("Go To Payment");
        GoToPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelcRoom1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Room1Info)))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelcRoom2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Room2Info)))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Room3Info))
                            .addComponent(SelcRoom3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GetInfo)
                            .addComponent(selectRT))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NoNights)
                        .addGap(18, 18, 18)
                        .addComponent(GetNight, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NoBeds)
                            .addComponent(NoMeal))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GetMeal)
                            .addComponent(GetBed))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MaxBed)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MaxMeal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(TPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GoToPayment)
                        .addGap(51, 51, 51))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Welcome)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Welcome)
                .addGap(11, 11, 11)
                .addComponent(selectRT)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelcRoom1)
                    .addComponent(SelcRoom2)
                    .addComponent(SelcRoom3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Room1Info)
                    .addComponent(Room2Info)
                    .addComponent(Room3Info))
                .addGap(42, 42, 42)
                .addComponent(GetInfo)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoNights)
                    .addComponent(GetNight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoBeds)
                    .addComponent(GetBed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaxBed))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoMeal)
                            .addComponent(GetMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaxMeal))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TPrice)
                            .addComponent(GoToPayment))
                        .addGap(37, 37, 37))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelcRoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelcRoom1ActionPerformed
        SelcRoom1.isSelected();
    }//GEN-LAST:event_SelcRoom1ActionPerformed

    private void SelcRoom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelcRoom2ActionPerformed
        SelcRoom2.isSelected();
    }//GEN-LAST:event_SelcRoom2ActionPerformed

    private void SelcRoom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelcRoom3ActionPerformed
        SelcRoom3.isSelected();
    }//GEN-LAST:event_SelcRoom3ActionPerformed

    private void Room1InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room1InfoActionPerformed
        JOptionPane.showMessageDialog(null, "Room Type : Standard \nPrice per Night : 750 \nBalacony : Small \nAC : Yes \nTV : Yes");
    }//GEN-LAST:event_Room1InfoActionPerformed

    private void Room2InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room2InfoActionPerformed
        JOptionPane.showMessageDialog(null, "Room Type : Deluxe \nPrice per Night : 1500 \nBalacony : Big \nAC : Yes \nTV : Yes");
    }//GEN-LAST:event_Room2InfoActionPerformed

    private void Room3InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room3InfoActionPerformed
        JOptionPane.showMessageDialog(null, "Room Type : Suite \nPrice per Night : 3000 \nBalacony : big \nAC : Yes \nTV : Yes");
    }//GEN-LAST:event_Room3InfoActionPerformed

    private void GetNightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetNightActionPerformed
//        Room1 r1=new Room1(); Room2 r2=new Room2() ;Room3 r3=new Room3();
        r1.no_of_nights=r2.no_of_nights=r3.no_of_nights=Integer.parseInt(GetNight.getText());
//        r2.no_of_nights=Integer.parseInt(GetNight.getText());
//        r3.no_of_nights=Integer.parseInt(GetNight.getText());
    }//GEN-LAST:event_GetNightActionPerformed

    private void GetBedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetBedActionPerformed
//        Room1 r1=new Room1(); Room2 r2=new Room2(); Room3 r3=new Room3();
        r1.bed_no=r2.bed_no=r3.bed_no=Integer.parseInt(GetBed.getText());
//        r2.bed_no=Integer.parseInt(GetBed.getText());
//        r3.bed_no=Integer.parseInt(GetBed.getText());
    }//GEN-LAST:event_GetBedActionPerformed

    private void GetMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetMealActionPerformed
//        Room1 r1=new Room1();Room2 r2=new Room2();Room3 r3=new Room3();
        r1.no_of_meals=r2.no_of_meals=r3.no_of_meals=Integer.parseInt(GetMeal.getText());
//        r2.no_of_meals=Integer.parseInt(GetMeal.getText());
//        r3.no_of_meals=Integer.parseInt(GetMeal.getText());
    }//GEN-LAST:event_GetMealActionPerformed

    private void TPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPriceActionPerformed
//        Room1 r1=new Room1();
//        Room2 r2=new Room2();
//        Room3 r3=new Room3();
        if(SelcRoom1.isSelected())
        {   
//            JOptionPane.showMessageDialog(null, Double.toString(r1.Total_Price()));
            JOptionPane.showMessageDialog(null, "Total Price : "+r1.Total_Price());
        }
        else if(SelcRoom2.isSelected())
            {
            JOptionPane.showMessageDialog(null, "Total Price : "+r2.Total_Price());}
        else if(SelcRoom3.isSelected())
            {
            JOptionPane.showMessageDialog(null, "Total Price : "+r3.Total_Price());}
    }//GEN-LAST:event_TPriceActionPerformed

    private void GoToPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToPaymentActionPerformed
        new Payment().setVisible(true);
    }//GEN-LAST:event_GoToPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GetBed;
    private javax.swing.JLabel GetInfo;
    private javax.swing.JTextField GetMeal;
    private javax.swing.JTextField GetNight;
    private javax.swing.JButton GoToPayment;
    private javax.swing.JLabel MaxBed;
    private javax.swing.JLabel MaxMeal;
    private javax.swing.JLabel NoBeds;
    private javax.swing.JLabel NoMeal;
    private javax.swing.JLabel NoNights;
    private javax.swing.JButton Room1Info;
    private javax.swing.JButton Room2Info;
    private javax.swing.JButton Room3Info;
    private javax.swing.JRadioButton SelcRoom1;
    private javax.swing.JRadioButton SelcRoom2;
    private javax.swing.JRadioButton SelcRoom3;
    private javax.swing.JButton TPrice;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel selectRT;
    // End of variables declaration//GEN-END:variables
}
